apiVersion: apps/v1
kind: Deployment
metadata:
  name: adeploy
  labels:
    app: adeploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: adeploy
  template:
    metadata:
      labels:
        app: adeploy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
