apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opslab
spec:
  selector:
    matchLabels:
      name: opslab
  template:
    metadata:
      labels:
        name: opslab
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
