```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  completions: 1                 # Number of tasks to complete
  backoffLimit: 4                # Number of retries on failure
  template:
    spec:
      containers:
      - name: job-container
        image: busybox            # Using BusyBox as a simple example
        command: ["echo", "Hello, Kubernetes Job is running!"]
      restartPolicy: Never         # Restart policy for the Pod on failure
```
