apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  completions: 1                 # Tamamlanması gereken görev sayısı
  backoffLimit: 4                # Başarısız olduğunda yeniden deneme sayısı
  template:
    spec:
      containers:
      - name: job-container
        image: busybox            # Basit bir örnek için BusyBox kullanıyoruz
        command: ["echo", "Merhaba, Kubernetes Job çalışıyor!"]
      restartPolicy: Never         # Pod'un başarısız olduğunda yeniden başlatma politikası

