apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test3
  name: test3
spec:
  containers:
  - image: nginx
    name: test3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
