apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        # Minimum CPU request: Pod requests at least 100m (millicore) of CPU
        cpu: 100m 
        # Minimum memory request: Pod requests at least 200Mi of memory
        memory: 200Mi
      limits:
        # Maximum CPU limit: Pod can use up to 200m (millicore) of CPU
        cpu: 200m
        # Maximum memory limit: Pod can use up to 400Mi of memory
        memory: 400Mi
