apiVersion: v1                                # API version, using v1 here.
kind: PersistentVolume                        # Resource type, PersistentVolume (PV).
metadata:
  name: app-data                              # Name of the PersistentVolume, must be unique within the cluster.
spec:
  capacity:
    storage: 10Mi                             # Storage capacity, set to 10 MiB here.
  accessModes:
    - ReadOnlyMany                            # Access mode; read-only access by many nodes.
  hostPath:
    path: "/srv/app-data"                     # File path on the host machine where the data is stored.
