apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080 #add nodePort: 30080 
  selector:
    run: nginx-pod
  type: NodePort
status:
  loadBalancer: {}
