apiVersion: v1                                # API version, using v1 here.
kind: Pod                                     # Resource type, in this case, a Pod.
metadata:
  name: task-pv-pod                           # Name of the Pod, must be unique.
spec:
  volumes:                                    # Volumes to be used within the Pod.
    - name: task-pv-storage                   # Name of the volume.
      persistentVolumeClaim:                  # Linking the volume to a Persistent Volume Claim.
        claimName: task-pv-claim              # Name of the PVC, using a previously created PVC.
  containers:                                 # Containers to run within the Pod.
    - name: task-pv-container                 # Name of the container.
      image: nginx                            # Docker image to use, here the nginx image is used.
      ports:                                  # Ports exposed by the container.
        - containerPort: 80                   # Exposes port 80 inside the container.
          name: "http-server"                 # Name given to the port, in this case, http-server.
      volumeMounts:                           # Volume mounts within the containers.
        - mountPath: "/usr/share/nginx/html"  # Path in the container where the volume will be mounted.
          name: task-pv-storage               # Name of the mounted volume, matching 'task-pv-storage' above.
