apiVersion: v1                     # API version, using the core API group 'v1' here.
kind: PersistentVolume             # Resource type, defining a persistent storage volume (PersistentVolume).
metadata:
  name: task-pv-volume             # Name of the PersistentVolume; this will be used as the resource identifier.
  labels:
    type: local                    # A custom label for the PersistentVolume. Labels are used to categorize resources.
spec:
  storageClassName: manual         # Storage class of the PersistentVolume. Here, a manually managed (manual) class is used.
  capacity:
    storage: 10Mi                  # Capacity of this PersistentVolume, set to 10 MiB.
  accessModes:
    - ReadWriteOnce                # Access mode; 'ReadWriteOnce' means the volume can be read/written by a single node.
  hostPath:
    path: "/mnt/data"              # Path to the directory on the host where the volume is stored; in this case, '/mnt/data' is used.
