apiVersion: v1                        # API version, using v1 here.
kind: PersistentVolumeClaim           # Resource type, in this case, PersistentVolumeClaim (PVC).
metadata:
  name: task-pv-claim                 # Name assigned to the PVC, must be unique.
spec:
  storageClassName: manual            # Storage class of the Persistent Volume to be bound to the PVC.
  accessModes:                        # Access modes for the PVC.
    - ReadWriteOnce                   # Access mode; in this case, the volume can be read and written by only one node.
  resources:
    requests:
      storage: 10Mi                   # Requested storage capacity, set to 10 MiB here.
