apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage        # Local depolama için StorageClass adı
provisioner: kubernetes.io/no-provisioner  # Yerel depolama sağlayıcısı, otomatik PV oluşturmaz
volumeBindingMode: WaitForFirstConsumer    # İlk kullanım talebi geldiğinde bağlama
reclaimPolicy: Retain                      # Silindiğinde PV'yi tutar

