apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage        # Name of the StorageClass for local storage
provisioner: kubernetes.io/no-provisioner  # Local storage provisioner, does not create PVs automatically
volumeBindingMode: WaitForFirstConsumer    # Binds the volume when a claim is made by the first consumer
reclaimPolicy: Retain                      # Retains the PV when the PVC is deleted
