apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume            # Name of the PersistentVolume
spec:
  capacity:
    storage: 100Mi                # Capacity of the PersistentVolume, set to 100 MiB
  accessModes:
    - ReadWriteOnce               # Access mode: allows read/write by a single node
  hostPath:
    path: "/mnt/data"             # Path on the host where the
