apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim              # Name of the PersistentVolumeClaim
spec:
  accessModes:
    - ReadWriteOnce               # Access mode: allows read/write by a single node
  resources:
    requests:
      storage: 90Mi               # Requested storage capacity, set to 90 MiB
