apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod                 # Name of the Pod
spec:
  volumes:
    - name: task-pv-storage         # Name of the volume
      persistentVolumeClaim:
        claimName: task-pv-claim    # Reference to the PersistentVolumeClaim
  containers:
    - name: task-pv-container       # Name of the container
      image: nginx                  # Docker image to be used (nginx)
      ports:
        - containerPort: 80         # Port exposed by the container
          name: "http-server"       # Name of the exposed port
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"  # Path inside the container to mount the volume
          name: task-pv-storage     # Name of the volume to be mounted, matching the volume defined above
