apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsstrategies
  labels:
    app: opsstrategies
spec:
  replicas: 5
  selector:
    matchLabels:
      app: opsstrategies
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: opsstrategies
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
