apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypod                       # Name of the container inside the Pod.
      image: redis                      # Image used for the container, here it's the Redis image.
      volumeMounts:
        - name: opslab                  # Name of the volume being mounted into the container.
          mountPath: "/etc/foo"         # Path inside the container where the volume will be mounted.
          readOnly: true                # The volume is mounted as read-only (write operations are restricted).
  volumes:                              # Section where volumes used by the pod are defined.
    - name: opslab                      # Name of the volume, referred to as "opslab".
      configMap:                        # Type of the volume, here it's created from a ConfigMap.
        name: myconfigmap               # Name of the ConfigMap used to create the volume, here it's "myconfigmap".
