apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: redis
      volumeMounts:
        - name: opslab                    # Defines which volumes the container will mount.
          mountPath: "/etc/foo"           # Directory path where the volume will be mounted, specified as "/etc/foo".
          readOnly: true                  # Mounts the volume as read-only (write operations are restricted).
  volumes:                                # Section where volumes belonging to the pod are defined.
    - name: opslab                        # Volume name, defined here as "opslab".
      configMap:                          # Volume type, using a ConfigMap to create the volume.
        name: myconfigmap                 # ConfigMap name, using the ConfigMap named "myconfigmap".
