apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app
spec:
  serviceName: "my-app-service"         # We define a stable service for network identity
  replicas: 3                           # Number of Pods
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx                    # Example application image (nginx)
        ports:
        - containerPort: 80
        volumeMounts:                   # Persistent storage definition
        - name: my-storage
          mountPath: "/usr/share/nginx/html"  # Path within the Pod for persistent use
  volumeClaimTemplates:                 # Persistent Storage definition
  - metadata:
      name: my-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]  # Read/Write access allowed for a single Pod
      storageClassName: "my-storage-class" # Storage class (must be pre-defined)
      resources:
        requests:
          storage: 1Gi                  # 1 GiB storage requested for each Pod
