apiVersion: v1
kind: Pod
metadata:
  name: opslab-env-multi-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: USER
          value: "admin"               # Environment variable USER is set with the value "admin"
    - name: busybox-container
      image: busybox
      command:
        - sleep                        # Command is specified line by line
        - "4000"
