apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80      # Servis portu
      targetPort: 80 # Pod içindeki hedef port
  type: ClusterIP

