apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80            # Servisin dinlediği dahili port
      targetPort: 80      # Pod'daki hedef port
      nodePort: 30080     # Dış dünyaya açılan port
  type: NodePort

