apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: opslab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx
        image: nginx

