apiVersion: v1
kind: Pod
metadata:
  name: ops
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}

  initContainers:
  - name: opsinit
    image: busybox
    command: ["sleep", "2000"]
    volumeMounts:
    - name: shared-volume
      mountPath: /mnt

  containers:
  - name: opsmain
    image: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html
