apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-port-from-namespace  # The NetworkPolicy name allows pods in the "internal" namespace to access a specific port in the "echo" namespace
  namespace: echo  # This NetworkPolicy is applied in the "echo" namespace
spec:
  podSelector:
    matchLabels: {}  # Targets all pods within the "echo" namespace, as no specific labels are specified
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: internal  # Allows traffic only from pods in namespaces labeled "name: internal"
    ports:
    - protocol: TCP  # Allows traffic only using the TCP protocol
      port: 9200  # Permits access only to traffic on port 9200
  policyTypes:
  - Ingress  # This NetworkPolicy controls only incoming traffic (Ingress)
