apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-container       # Name of the container
      image: nginx                 # Docker image to use, here it's Nginx
      env:
        - name: USERNAME           # Environment variable for the username
          valueFrom:
            secretKeyRef:          # Reference to a Secret
              name: my-secret      # Name of the Secret
              key: username        # Key within the Secret to retrieve the value
        - name: PASSWORD           # Environment variable for the password
          valueFrom:
            secretKeyRef:          # Reference to a Secret
              name: my-secret      # Name of the Secret
              key: password        # Key within the Secret to retrieve the value
