apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-container
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret      # Secret'ın adı
              key: username        # Secret içinde kullanılan anahtar
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password

