apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    version: blue   # green for transition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

